### ISSUE TITLE
Repeating Email Searching: Feature

### ISSUE THREAD

**Issue by Name277** [ShaneLee/Youtube-Email-Bulk-Downloader#2]
This isn't really an issue or error with the script, I have been struggling with trying to find out how I could make the script automatically find the word 'uploaded' for example in an email and if there isn't any emails with the word 'uploaded' how could I modify the script in order for it to repeat searching until it finds the word 'uploaded' and then continues? I don't think this is a script issue just a new feature I want to implement if it could be possible, thanks.

**Comment by ShaneLee** [comment]
When you say you want the script to repeat if it doesn't find any e-mails with 'uploaded' in them. Do you want it to wait for a period and then run the script again?

**Comment by Name277** [comment]
yes, so if it doesn't find any emails with 'uploaded' or any emails in the inbox at all, I want the script to rerun again, if it needs a wait then that is fine too.

**Comment by ShaneLee** [comment]
Yeah cool - if you have a look at this commit https://github.com/ShaneLee/Youtube-Email-Bulk-Downloader/commit/58070ff41cf59f828f64b5f06732dad3f5ce1a97

It should do what you want. 

It's on a feature branch called feature/uploaded

Let me know if that works for you.

**Comment by Name277** [comment]
I tried it out and when the inbox was empty it did rerun but for some reason when I recieved an email with 'upload' it send me this error:

initial_value must be str or None, not bytes
Traceback (most recent call last):
  File "getvideo.py", line 17, in <module>
    getvideos()
  File "getvideo.py", line 11, in getvideos
    getvideos()
  File "getvideo.py", line 11, in getvideos
    getvideos()
  File "getvideo.py", line 12, in getvideos
    for link in links:
TypeError: 'NoneType' object is not iterable

This is the code I used on the getvideo.py file:

import pytube
import yt_email
import time


def getvideos():
    links = yt_email.get_video_links()
    if links == []:
        time.sleep(60)
        print('60')
        getvideos()
    for link in links:
        print(link)
        pytube.YouTube(link).streams.first().download('.')
    
if __name__ == '__main__':
    getvideos()

thanks for the replay, I don't know why that error occured but after the 60 seconds were over and it did find an email with 'upload' that error occured.

Edit: Sorry the code was a bit messy, here is a pastebin source:

https://pastebin.com/im7sy7bf

**Comment by Name277** [comment]
For some reason I had to place a .decode('utf8') on the yt_email.py because the link couldn't be detected properly I think. Other than that this solved the issue I had, thanks a lot!

**Comment by ShaneLee** [comment]
No worries - glad you got it sorted 

Thanks 

Shane
